/* tslint:disable */
/* eslint-disable */
/**
 * OasisExplorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Info,
    InfoFromJSON,
    InfoToJSON,
} from '../models';

/**
 *
 */
export class AppInfoApi extends runtime.BaseAPI {

    /**
     */
    async getInfoRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Info>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/data/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoFromJSON(jsonValue));
    }

    /**
     */
    async getInfo(initOverrides?: RequestInit): Promise<Info> {
        const response = await this.getInfoRaw(initOverrides);
        return await response.value();
    }

}
