# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: master # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TYPESCRIPT_STANDARD
  - DOCKERFILE_HADOLINT
  - CREDENTIALS_SECRETLINT
DISABLE:
  - COPYPASTE # Comment to disable checks of abusive copy-pastes
  - SPELL # Comment to disable checks of spelling mistakes # - SPELL # Uncomment to disable checks of spelling mistakes
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .husky
  - build
  - build-ext
  - cypress-coverage
  - .nyc_output
  - .parcel-cache
FILTER_REGEX_EXCLUDE: (LICENCE|\.codecov.yml|CHANGELOG.md|src/vendors/explorer/*|src/vendors/oasisscan/*)
SHOW_ELAPSED_TIME: true
PRE_COMMANDS:
  - command: yarn install
    cwd: 'root' # Will be run at the root of Mega-Linter docker image
