version: '3.9'
services:
  oasis-node-testnet:
    build: docker/oasis-node
    # restart: always
    volumes:
      - oasis-node-data:/node/data:z
      # Oasis-node config file
      - ./docker/oasis-node/config-testnet.yml:/node/etc/config.yml:z
      # Genesis file
      - ./docker/genesis-testnet.json:/node/etc/genesis.json:z
      # Expose sock
  oasis-explorer:
    build: docker/oasis-explorer
    restart: always
    ports:
      - '127.0.0.1:9001:9001'
    volumes:
      - oasis-node-data:/node/data:z
      - ./docker/genesis-testnet.json:/genesis.json:z
      - ./docker/oasis-explorer/config-testnet.json:/.secrets/config.json:z
  envoy:
    image: envoyproxy/envoy:v1.20.1
    ports:
      - '127.0.0.1:42280:42280'
      - '127.0.0.1:42281:42281'
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level upstream:debug,connection:trace
    environment:
      ENVOY_UID: 0
      ENVOY_GID: 0
    volumes:
      - oasis-node-data:/node/data:z
      - ./docker/envoy.yaml:/etc/envoy/envoy.yaml:z
  explorer-postgres:
    image: postgres
    restart: always
    volumes:
      - explorer-postgres-data:/var/lib/postgresql/data:z
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: oasis
      POSTGRES_USER: oasis
      POSTGRES_DATABASE: oasis
  explorer-clickhouse:
    image: yandex/clickhouse-server
    restart: always
    volumes:
      - explorer-clickhouse-data:/var/lib/clickhouse:z
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'

volumes:
  oasis-node-data:
  postgres-data:
  explorer-postgres-data:
  explorer-clickhouse-data:
