/* tslint:disable */
/* eslint-disable */
/**
 * OasisExplorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ValidatorMegiaInfo
 */
export interface ValidatorMegiaInfo {
    /**
    *
    * @type {string}
    * @memberof ValidatorMegiaInfo
    */
    website_link?: string;
    /**
    *
    * @type {string}
    * @memberof ValidatorMegiaInfo
    */
    email_address?: string;
    /**
    *
    * @type {string}
    * @memberof ValidatorMegiaInfo
    */
    twitter_acc?: string;
    /**
    *
    * @type {string}
    * @memberof ValidatorMegiaInfo
    */
    tg_chat?: string;
    /**
    *
    * @type {string}
    * @memberof ValidatorMegiaInfo
    */
    medium_link?: string;
}

export function ValidatorMegiaInfoFromJSON(json: any): ValidatorMegiaInfo {
    return ValidatorMegiaInfoFromJSONTyped(json, false);
}

export function ValidatorMegiaInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorMegiaInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'website_link': !exists(json, 'website_link') ? undefined : json['website_link'],
        'email_address': !exists(json, 'email_address') ? undefined : json['email_address'],
        'twitter_acc': !exists(json, 'twitter_acc') ? undefined : json['twitter_acc'],
        'tg_chat': !exists(json, 'tg_chat') ? undefined : json['tg_chat'],
        'medium_link': !exists(json, 'medium_link') ? undefined : json['medium_link'],
    };
}

export function ValidatorMegiaInfoToJSON(value?: ValidatorMegiaInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'website_link': value.website_link,
        'email_address': value.email_address,
        'twitter_acc': value.twitter_acc,
        'tg_chat': value.tg_chat,
        'medium_link': value.medium_link,
    };
}
