/* tslint:disable */
/* eslint-disable */
/**
 * Oasisscan API
 * https://github.com/bitcat365/oasisscan-backend#readme
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CtxRow,
    CtxRowFromJSON,
    CtxRowFromJSONTyped,
    CtxRowToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003Data
 */
export interface InlineResponse2003Data {
    /**
     * 
     * @type {CtxRow}
     * @memberof InlineResponse2003Data
     */
    ctx: CtxRow;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Data
     */
    runtimeName: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Data
     */
    round: number;
}

export function InlineResponse2003DataFromJSON(json: any): InlineResponse2003Data {
    return InlineResponse2003DataFromJSONTyped(json, false);
}

export function InlineResponse2003DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003Data {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ctx': CtxRowFromJSON(json['ctx']),
        'runtimeName': json['runtimeName'],
        'round': json['round'],
    };
}

export function InlineResponse2003DataToJSON(value?: InlineResponse2003Data | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ctx': CtxRowToJSON(value.ctx),
        'runtimeName': value.runtimeName,
        'round': value.round,
    };
}


