/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountListAllOfAccounts } from './AccountListAllOfAccounts';
import {
    AccountListAllOfAccountsFromJSON,
    AccountListAllOfAccountsFromJSONTyped,
    AccountListAllOfAccountsToJSON,
    AccountListAllOfAccountsToJSONTyped,
} from './AccountListAllOfAccounts';

/**
 * 
 * @export
 * @interface AccountList
 */
export interface AccountList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof AccountList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof AccountList
     */
    is_total_count_clipped: boolean;
    /**
     * 
     * @type {Array<AccountListAllOfAccounts>}
     * @memberof AccountList
     */
    accounts: Array<AccountListAllOfAccounts>;
}

/**
 * Check if a given object implements the AccountList interface.
 */
export function instanceOfAccountList(value: object): value is AccountList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function AccountListFromJSON(json: any): AccountList {
    return AccountListFromJSONTyped(json, false);
}

export function AccountListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'accounts': ((json['accounts'] as Array<any>).map(AccountListAllOfAccountsFromJSON)),
    };
}

export function AccountListToJSON(json: any): AccountList {
    return AccountListToJSONTyped(json, false);
}

export function AccountListToJSONTyped(value?: AccountList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'accounts': ((value['accounts'] as Array<any>).map(AccountListAllOfAccountsToJSON)),
    };
}

