/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActiveAccounts } from './ActiveAccounts';
import {
    ActiveAccountsFromJSON,
    ActiveAccountsFromJSONTyped,
    ActiveAccountsToJSON,
    ActiveAccountsToJSONTyped,
} from './ActiveAccounts';

/**
 * A list of daily unique active account windows.
 * 
 * @export
 * @interface ActiveAccountsList
 */
export interface ActiveAccountsList {
    /**
     * 
     * @type {number}
     * @memberof ActiveAccountsList
     */
    window_size_seconds: number;
    /**
     * The list of daily unique active account windows.
     * @type {Array<ActiveAccounts>}
     * @memberof ActiveAccountsList
     */
    windows: Array<ActiveAccounts>;
}

/**
 * Check if a given object implements the ActiveAccountsList interface.
 */
export function instanceOfActiveAccountsList(value: object): value is ActiveAccountsList {
    if (!('window_size_seconds' in value) || value['window_size_seconds'] === undefined) return false;
    if (!('windows' in value) || value['windows'] === undefined) return false;
    return true;
}

export function ActiveAccountsListFromJSON(json: any): ActiveAccountsList {
    return ActiveAccountsListFromJSONTyped(json, false);
}

export function ActiveAccountsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveAccountsList {
    if (json == null) {
        return json;
    }
    return {
        
        'window_size_seconds': json['window_size_seconds'],
        'windows': ((json['windows'] as Array<any>).map(ActiveAccountsFromJSON)),
    };
}

export function ActiveAccountsListToJSON(json: any): ActiveAccountsList {
    return ActiveAccountsListToJSONTyped(json, false);
}

export function ActiveAccountsListToJSONTyped(value?: ActiveAccountsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_size_seconds': value['window_size_seconds'],
        'windows': ((value['windows'] as Array<any>).map(ActiveAccountsToJSON)),
    };
}

