/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A delegation.
 * 
 * @export
 * @interface Delegation
 */
export interface Delegation {
    /**
     * The amount of tokens delegated in base units.
     * @type {string}
     * @memberof Delegation
     */
    amount: string;
    /**
     * The shares of tokens delegated.
     * @type {string}
     * @memberof Delegation
     */
    shares: string;
    /**
     * The delegatee (validator) address.
     * @type {string}
     * @memberof Delegation
     */
    validator: string;
    /**
     * The delegator address.
     * @type {string}
     * @memberof Delegation
     */
    delegator: string;
}

/**
 * Check if a given object implements the Delegation interface.
 */
export function instanceOfDelegation(value: object): value is Delegation {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('shares' in value) || value['shares'] === undefined) return false;
    if (!('validator' in value) || value['validator'] === undefined) return false;
    if (!('delegator' in value) || value['delegator'] === undefined) return false;
    return true;
}

export function DelegationFromJSON(json: any): Delegation {
    return DelegationFromJSONTyped(json, false);
}

export function DelegationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Delegation {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'shares': json['shares'],
        'validator': json['validator'],
        'delegator': json['delegator'],
    };
}

export function DelegationToJSON(json: any): Delegation {
    return DelegationToJSONTyped(json, false);
}

export function DelegationToJSONTyped(value?: Delegation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'shares': value['shares'],
        'validator': value['validator'],
        'delegator': value['delegator'],
    };
}

