/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DelegationListAllOfDelegations } from './DelegationListAllOfDelegations';
import {
    DelegationListAllOfDelegationsFromJSON,
    DelegationListAllOfDelegationsFromJSONTyped,
    DelegationListAllOfDelegationsToJSON,
    DelegationListAllOfDelegationsToJSONTyped,
} from './DelegationListAllOfDelegations';

/**
 * 
 * @export
 * @interface DelegationList
 */
export interface DelegationList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof DelegationList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof DelegationList
     */
    is_total_count_clipped: boolean;
    /**
     * 
     * @type {Array<DelegationListAllOfDelegations>}
     * @memberof DelegationList
     */
    delegations: Array<DelegationListAllOfDelegations>;
}

/**
 * Check if a given object implements the DelegationList interface.
 */
export function instanceOfDelegationList(value: object): value is DelegationList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('delegations' in value) || value['delegations'] === undefined) return false;
    return true;
}

export function DelegationListFromJSON(json: any): DelegationList {
    return DelegationListFromJSONTyped(json, false);
}

export function DelegationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DelegationList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'delegations': ((json['delegations'] as Array<any>).map(DelegationListAllOfDelegationsFromJSON)),
    };
}

export function DelegationListToJSON(json: any): DelegationList {
    return DelegationListToJSONTyped(json, false);
}

export function DelegationListToJSONTyped(value?: DelegationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'delegations': ((value['delegations'] as Array<any>).map(DelegationListAllOfDelegationsToJSON)),
    };
}

