/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityListAllOfEntities } from './EntityListAllOfEntities';
import {
    EntityListAllOfEntitiesFromJSON,
    EntityListAllOfEntitiesFromJSONTyped,
    EntityListAllOfEntitiesToJSON,
    EntityListAllOfEntitiesToJSONTyped,
} from './EntityListAllOfEntities';

/**
 * 
 * @export
 * @interface EntityList
 */
export interface EntityList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof EntityList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof EntityList
     */
    is_total_count_clipped: boolean;
    /**
     * 
     * @type {Array<EntityListAllOfEntities>}
     * @memberof EntityList
     */
    entities: Array<EntityListAllOfEntities>;
}

/**
 * Check if a given object implements the EntityList interface.
 */
export function instanceOfEntityList(value: object): value is EntityList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('entities' in value) || value['entities'] === undefined) return false;
    return true;
}

export function EntityListFromJSON(json: any): EntityList {
    return EntityListFromJSONTyped(json, false);
}

export function EntityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'entities': ((json['entities'] as Array<any>).map(EntityListAllOfEntitiesFromJSON)),
    };
}

export function EntityListToJSON(json: any): EntityList {
    return EntityListToJSONTyped(json, false);
}

export function EntityListToJSONTyped(value?: EntityList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'entities': ((value['entities'] as Array<any>).map(EntityListAllOfEntitiesToJSON)),
    };
}

