/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EpochListAllOfEpochs
 */
export interface EpochListAllOfEpochs {
    /**
     * The epoch number.
     * @type {number}
     * @memberof EpochListAllOfEpochs
     */
    id: number;
    /**
     * The (inclusive) height at which this epoch started.
     * @type {number}
     * @memberof EpochListAllOfEpochs
     */
    start_height: number;
    /**
     * The (inclusive) height at which this epoch ended. Omitted if the epoch is still active.
     * @type {number}
     * @memberof EpochListAllOfEpochs
     */
    end_height?: number;
}

/**
 * Check if a given object implements the EpochListAllOfEpochs interface.
 */
export function instanceOfEpochListAllOfEpochs(value: object): value is EpochListAllOfEpochs {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('start_height' in value) || value['start_height'] === undefined) return false;
    return true;
}

export function EpochListAllOfEpochsFromJSON(json: any): EpochListAllOfEpochs {
    return EpochListAllOfEpochsFromJSONTyped(json, false);
}

export function EpochListAllOfEpochsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpochListAllOfEpochs {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'start_height': json['start_height'],
        'end_height': json['end_height'] == null ? undefined : json['end_height'],
    };
}

export function EpochListAllOfEpochsToJSON(json: any): EpochListAllOfEpochs {
    return EpochListAllOfEpochsToJSONTyped(json, false);
}

export function EpochListAllOfEpochsToJSONTyped(value?: EpochListAllOfEpochs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'start_height': value['start_height'],
        'end_height': value['end_height'],
    };
}

