/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpochListAllOfEpochs } from './EpochListAllOfEpochs';
import {
    EpochListAllOfEpochsFromJSON,
    EpochListAllOfEpochsFromJSONTyped,
    EpochListAllOfEpochsToJSON,
    EpochListAllOfEpochsToJSONTyped,
} from './EpochListAllOfEpochs';

/**
 * 
 * @export
 * @interface EpochList
 */
export interface EpochList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof EpochList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof EpochList
     */
    is_total_count_clipped: boolean;
    /**
     * 
     * @type {Array<EpochListAllOfEpochs>}
     * @memberof EpochList
     */
    epochs: Array<EpochListAllOfEpochs>;
}

/**
 * Check if a given object implements the EpochList interface.
 */
export function instanceOfEpochList(value: object): value is EpochList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('epochs' in value) || value['epochs'] === undefined) return false;
    return true;
}

export function EpochListFromJSON(json: any): EpochList {
    return EpochListFromJSONTyped(json, false);
}

export function EpochListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpochList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'epochs': ((json['epochs'] as Array<any>).map(EpochListAllOfEpochsFromJSON)),
    };
}

export function EpochListToJSON(json: any): EpochList {
    return EpochListToJSONTyped(json, false);
}

export function EpochListToJSONTyped(value?: EpochList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'epochs': ((value['epochs'] as Array<any>).map(EpochListAllOfEpochsToJSON)),
    };
}

