/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Escrow
 */
export interface Escrow {
    /**
     * The amount of tokens that are delegated to this validator account, and are NOT in the process of debonding.
     * @type {string}
     * @memberof Escrow
     */
    active_balance?: string;
    /**
     * The shares of tokens that are delegated to this validator account, and are NOT in the process of debonding.
     * @type {string}
     * @memberof Escrow
     */
    active_shares?: string;
    /**
     * The amount of tokens that are delegated to this validator account, but are also in the process of debonding (i.e. they will be unstaked within ~2 weeks).
     * @type {string}
     * @memberof Escrow
     */
    debonding_balance?: string;
    /**
     * The shares of tokens that are delegated to this validator account, but are also in the process of debonding (i.e. they will be unstaked within ~2 weeks).
     * @type {string}
     * @memberof Escrow
     */
    debonding_shares?: string;
    /**
     * The amount of token this validator has delegated to itself, and are NOT in the process of debonding.
     * @type {string}
     * @memberof Escrow
     */
    self_delegation_balance?: string;
    /**
     * The shares of tokens this validator has delegated to itself, and are NOT in the process of debonding.
     * @type {string}
     * @memberof Escrow
     */
    self_delegation_shares?: string;
    /**
     * The active_balance of this validator account 24 hours ago.
     * @type {string}
     * @memberof Escrow
     */
    active_balance_24?: string;
    /**
     * The number of accounts that have delegated token to this account.
     * @type {number}
     * @memberof Escrow
     */
    num_delegators?: number;
}

/**
 * Check if a given object implements the Escrow interface.
 */
export function instanceOfEscrow(value: object): value is Escrow {
    return true;
}

export function EscrowFromJSON(json: any): Escrow {
    return EscrowFromJSONTyped(json, false);
}

export function EscrowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Escrow {
    if (json == null) {
        return json;
    }
    return {
        
        'active_balance': json['active_balance'] == null ? undefined : json['active_balance'],
        'active_shares': json['active_shares'] == null ? undefined : json['active_shares'],
        'debonding_balance': json['debonding_balance'] == null ? undefined : json['debonding_balance'],
        'debonding_shares': json['debonding_shares'] == null ? undefined : json['debonding_shares'],
        'self_delegation_balance': json['self_delegation_balance'] == null ? undefined : json['self_delegation_balance'],
        'self_delegation_shares': json['self_delegation_shares'] == null ? undefined : json['self_delegation_shares'],
        'active_balance_24': json['active_balance_24'] == null ? undefined : json['active_balance_24'],
        'num_delegators': json['num_delegators'] == null ? undefined : json['num_delegators'],
    };
}

export function EscrowToJSON(json: any): Escrow {
    return EscrowToJSONTyped(json, false);
}

export function EscrowToJSONTyped(value?: Escrow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_balance': value['active_balance'],
        'active_shares': value['active_shares'],
        'debonding_balance': value['debonding_balance'],
        'debonding_shares': value['debonding_shares'],
        'self_delegation_balance': value['self_delegation_balance'],
        'self_delegation_shares': value['self_delegation_shares'],
        'active_balance_24': value['active_balance_24'],
        'num_delegators': value['num_delegators'],
    };
}

