/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvmTokenListAllOfEvmTokens } from './EvmTokenListAllOfEvmTokens';
import {
    EvmTokenListAllOfEvmTokensFromJSON,
    EvmTokenListAllOfEvmTokensFromJSONTyped,
    EvmTokenListAllOfEvmTokensToJSON,
    EvmTokenListAllOfEvmTokensToJSONTyped,
} from './EvmTokenListAllOfEvmTokens';

/**
 * 
 * @export
 * @interface EvmTokenList
 */
export interface EvmTokenList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof EvmTokenList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof EvmTokenList
     */
    is_total_count_clipped: boolean;
    /**
     * A list of L2 EVM tokens (ERC-20, ERC-721, ...).
     * @type {Array<EvmTokenListAllOfEvmTokens>}
     * @memberof EvmTokenList
     */
    evm_tokens: Array<EvmTokenListAllOfEvmTokens>;
}

/**
 * Check if a given object implements the EvmTokenList interface.
 */
export function instanceOfEvmTokenList(value: object): value is EvmTokenList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('evm_tokens' in value) || value['evm_tokens'] === undefined) return false;
    return true;
}

export function EvmTokenListFromJSON(json: any): EvmTokenList {
    return EvmTokenListFromJSONTyped(json, false);
}

export function EvmTokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmTokenList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'evm_tokens': ((json['evm_tokens'] as Array<any>).map(EvmTokenListAllOfEvmTokensFromJSON)),
    };
}

export function EvmTokenListToJSON(json: any): EvmTokenList {
    return EvmTokenListToJSONTyped(json, false);
}

export function EvmTokenListToJSONTyped(value?: EvmTokenList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'evm_tokens': ((value['evm_tokens'] as Array<any>).map(EvmTokenListAllOfEvmTokensToJSON)),
    };
}

