/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The target propotocol versions for this upgrade proposal.
 * @export
 * @interface ProposalTarget
 */
export interface ProposalTarget {
    /**
     * 
     * @type {string}
     * @memberof ProposalTarget
     */
    consensus_protocol?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalTarget
     */
    runtime_host_protocol?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposalTarget
     */
    runtime_committee_protocol?: string;
}

/**
 * Check if a given object implements the ProposalTarget interface.
 */
export function instanceOfProposalTarget(value: object): value is ProposalTarget {
    return true;
}

export function ProposalTargetFromJSON(json: any): ProposalTarget {
    return ProposalTargetFromJSONTyped(json, false);
}

export function ProposalTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProposalTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'consensus_protocol': json['consensus_protocol'] == null ? undefined : json['consensus_protocol'],
        'runtime_host_protocol': json['runtime_host_protocol'] == null ? undefined : json['runtime_host_protocol'],
        'runtime_committee_protocol': json['runtime_committee_protocol'] == null ? undefined : json['runtime_committee_protocol'],
    };
}

export function ProposalTargetToJSON(json: any): ProposalTarget {
    return ProposalTargetToJSONTyped(json, false);
}

export function ProposalTargetToJSONTyped(value?: ProposalTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consensus_protocol': value['consensus_protocol'],
        'runtime_host_protocol': value['runtime_host_protocol'],
        'runtime_committee_protocol': value['runtime_committee_protocol'],
    };
}

