/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RuntimeBlockListAllOfBlocks } from './RuntimeBlockListAllOfBlocks';
import {
    RuntimeBlockListAllOfBlocksFromJSON,
    RuntimeBlockListAllOfBlocksFromJSONTyped,
    RuntimeBlockListAllOfBlocksToJSON,
    RuntimeBlockListAllOfBlocksToJSONTyped,
} from './RuntimeBlockListAllOfBlocks';

/**
 * 
 * @export
 * @interface RuntimeBlockList
 */
export interface RuntimeBlockList {
    /**
     * The total number of records that match the query, i.e. the number of records
     * the query would return with limit=infinity.
     * 
     * @type {number}
     * @memberof RuntimeBlockList
     */
    total_count: number;
    /**
     * Whether total_count is clipped for performance reasons.
     * @type {boolean}
     * @memberof RuntimeBlockList
     */
    is_total_count_clipped: boolean;
    /**
     * 
     * @type {Array<RuntimeBlockListAllOfBlocks>}
     * @memberof RuntimeBlockList
     */
    blocks: Array<RuntimeBlockListAllOfBlocks>;
}

/**
 * Check if a given object implements the RuntimeBlockList interface.
 */
export function instanceOfRuntimeBlockList(value: object): value is RuntimeBlockList {
    if (!('total_count' in value) || value['total_count'] === undefined) return false;
    if (!('is_total_count_clipped' in value) || value['is_total_count_clipped'] === undefined) return false;
    if (!('blocks' in value) || value['blocks'] === undefined) return false;
    return true;
}

export function RuntimeBlockListFromJSON(json: any): RuntimeBlockList {
    return RuntimeBlockListFromJSONTyped(json, false);
}

export function RuntimeBlockListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeBlockList {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'],
        'is_total_count_clipped': json['is_total_count_clipped'],
        'blocks': ((json['blocks'] as Array<any>).map(RuntimeBlockListAllOfBlocksFromJSON)),
    };
}

export function RuntimeBlockListToJSON(json: any): RuntimeBlockList {
    return RuntimeBlockListToJSONTyped(json, false);
}

export function RuntimeBlockListToJSONTyped(value?: RuntimeBlockList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'is_total_count_clipped': value['is_total_count_clipped'],
        'blocks': ((value['blocks'] as Array<any>).map(RuntimeBlockListAllOfBlocksToJSON)),
    };
}

