/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenHolderListAllOfHolders
 */
export interface TokenHolderListAllOfHolders {
    /**
     * The Oasis address of the account holder.
     * @type {string}
     * @memberof TokenHolderListAllOfHolders
     */
    holder_address: string;
    /**
     * The Ethereum address of the same account holder, if meaningfully defined.
     * @type {string}
     * @memberof TokenHolderListAllOfHolders
     */
    eth_holder_address?: string;
    /**
     * Number of tokens held, in base units.
     * @type {string}
     * @memberof TokenHolderListAllOfHolders
     */
    balance: string;
}

/**
 * Check if a given object implements the TokenHolderListAllOfHolders interface.
 */
export function instanceOfTokenHolderListAllOfHolders(value: object): value is TokenHolderListAllOfHolders {
    if (!('holder_address' in value) || value['holder_address'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function TokenHolderListAllOfHoldersFromJSON(json: any): TokenHolderListAllOfHolders {
    return TokenHolderListAllOfHoldersFromJSONTyped(json, false);
}

export function TokenHolderListAllOfHoldersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenHolderListAllOfHolders {
    if (json == null) {
        return json;
    }
    return {
        
        'holder_address': json['holder_address'],
        'eth_holder_address': json['eth_holder_address'] == null ? undefined : json['eth_holder_address'],
        'balance': json['balance'],
    };
}

export function TokenHolderListAllOfHoldersToJSON(json: any): TokenHolderListAllOfHolders {
    return TokenHolderListAllOfHoldersToJSONTyped(json, false);
}

export function TokenHolderListAllOfHoldersToJSONTyped(value?: TokenHolderListAllOfHolders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'holder_address': value['holder_address'],
        'eth_holder_address': value['eth_holder_address'],
        'balance': value['balance'],
    };
}

