/* tslint:disable */
/* eslint-disable */
/**
 * Oasis Nexus API V1
 * An API for accessing indexed data from the Oasis Network.  <!-- Acts as a separator after search in sidebar --> # Endpoints 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxVolume
 */
export interface TxVolume {
    /**
     * The end timestamp for this daily transaction volume measurement.
     * @type {string}
     * @memberof TxVolume
     */
    window_end: string;
    /**
     * The transaction volume for this window.
     * @type {number}
     * @memberof TxVolume
     */
    tx_volume: number;
}

/**
 * Check if a given object implements the TxVolume interface.
 */
export function instanceOfTxVolume(value: object): value is TxVolume {
    if (!('window_end' in value) || value['window_end'] === undefined) return false;
    if (!('tx_volume' in value) || value['tx_volume'] === undefined) return false;
    return true;
}

export function TxVolumeFromJSON(json: any): TxVolume {
    return TxVolumeFromJSONTyped(json, false);
}

export function TxVolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxVolume {
    if (json == null) {
        return json;
    }
    return {
        
        'window_end': json['window_end'],
        'tx_volume': json['tx_volume'],
    };
}

export function TxVolumeToJSON(json: any): TxVolume {
    return TxVolumeToJSONTyped(json, false);
}

export function TxVolumeToJSONTyped(value?: TxVolume | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_end': value['window_end'],
        'tx_volume': value['tx_volume'],
    };
}

