/* eslint-disable no-restricted-imports */
// Auto-generated by "yarn fix-grommet-icons-types"
// This is needed because grommet-icons does not define types for each individual icon file

declare module 'grommet-icons/es6/icons/Accessibility' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Accessibility: Icon
}

declare module 'grommet-icons/es6/icons/Achievement' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Achievement: Icon
}

declare module 'grommet-icons/es6/icons/Action' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Action: Icon
}

declare module 'grommet-icons/es6/icons/Actions' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Actions: Icon
}

declare module 'grommet-icons/es6/icons/Ad' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ad: Icon
}

declare module 'grommet-icons/es6/icons/AddCircle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const AddCircle: Icon
}

declare module 'grommet-icons/es6/icons/Add' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Add: Icon
}

declare module 'grommet-icons/es6/icons/Aed' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Aed: Icon
}

declare module 'grommet-icons/es6/icons/Aggregate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Aggregate: Icon
}

declare module 'grommet-icons/es6/icons/AidOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const AidOption: Icon
}

declare module 'grommet-icons/es6/icons/Aid' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Aid: Icon
}

declare module 'grommet-icons/es6/icons/Alarm' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Alarm: Icon
}

declare module 'grommet-icons/es6/icons/Alert' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Alert: Icon
}

declare module 'grommet-icons/es6/icons/Amazon' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Amazon: Icon
}

declare module 'grommet-icons/es6/icons/Amex' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Amex: Icon
}

declare module 'grommet-icons/es6/icons/Analytics' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Analytics: Icon
}

declare module 'grommet-icons/es6/icons/Anchor' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Anchor: Icon
}

declare module 'grommet-icons/es6/icons/Android' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Android: Icon
}

declare module 'grommet-icons/es6/icons/Announce' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Announce: Icon
}

declare module 'grommet-icons/es6/icons/AppleAppStore' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const AppleAppStore: Icon
}

declare module 'grommet-icons/es6/icons/Apple' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Apple: Icon
}

declare module 'grommet-icons/es6/icons/AppsRounded' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const AppsRounded: Icon
}

declare module 'grommet-icons/es6/icons/Apps' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Apps: Icon
}

declare module 'grommet-icons/es6/icons/Archive' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Archive: Icon
}

declare module 'grommet-icons/es6/icons/Archlinux' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Archlinux: Icon
}

declare module 'grommet-icons/es6/icons/Article' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Article: Icon
}

declare module 'grommet-icons/es6/icons/Aruba' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Aruba: Icon
}

declare module 'grommet-icons/es6/icons/Ascend' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ascend: Icon
}

declare module 'grommet-icons/es6/icons/Ascending' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ascending: Icon
}

declare module 'grommet-icons/es6/icons/AssistListening' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const AssistListening: Icon
}

declare module 'grommet-icons/es6/icons/Atm' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Atm: Icon
}

declare module 'grommet-icons/es6/icons/Attachment' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Attachment: Icon
}

declare module 'grommet-icons/es6/icons/Attraction' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Attraction: Icon
}

declare module 'grommet-icons/es6/icons/Baby' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Baby: Icon
}

declare module 'grommet-icons/es6/icons/BackTen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BackTen: Icon
}

declare module 'grommet-icons/es6/icons/BarChart' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BarChart: Icon
}

declare module 'grommet-icons/es6/icons/Bar' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bar: Icon
}

declare module 'grommet-icons/es6/icons/Basket' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Basket: Icon
}

declare module 'grommet-icons/es6/icons/Beacon' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Beacon: Icon
}

declare module 'grommet-icons/es6/icons/Bike' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bike: Icon
}

declare module 'grommet-icons/es6/icons/Bitcoin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bitcoin: Icon
}

declare module 'grommet-icons/es6/icons/BladesHorizontal' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BladesHorizontal: Icon
}

declare module 'grommet-icons/es6/icons/BladesVertical' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BladesVertical: Icon
}

declare module 'grommet-icons/es6/icons/BlockQuote' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BlockQuote: Icon
}

declare module 'grommet-icons/es6/icons/Blog' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Blog: Icon
}

declare module 'grommet-icons/es6/icons/Bluetooth' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bluetooth: Icon
}

declare module 'grommet-icons/es6/icons/Bold' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bold: Icon
}

declare module 'grommet-icons/es6/icons/Book' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Book: Icon
}

declare module 'grommet-icons/es6/icons/Bookmark' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bookmark: Icon
}

declare module 'grommet-icons/es6/icons/BottomCorner' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BottomCorner: Icon
}

declare module 'grommet-icons/es6/icons/Braille' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Braille: Icon
}

declare module 'grommet-icons/es6/icons/Briefcase' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Briefcase: Icon
}

declare module 'grommet-icons/es6/icons/Brush' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Brush: Icon
}

declare module 'grommet-icons/es6/icons/Bucket' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bucket: Icon
}

declare module 'grommet-icons/es6/icons/Bug' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bug: Icon
}

declare module 'grommet-icons/es6/icons/Bundle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bundle: Icon
}

declare module 'grommet-icons/es6/icons/Bus' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Bus: Icon
}

declare module 'grommet-icons/es6/icons/BusinessService' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const BusinessService: Icon
}

declare module 'grommet-icons/es6/icons/Cafeteria' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cafeteria: Icon
}

declare module 'grommet-icons/es6/icons/Calculator' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Calculator: Icon
}

declare module 'grommet-icons/es6/icons/Calendar' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Calendar: Icon
}

declare module 'grommet-icons/es6/icons/Camera' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Camera: Icon
}

declare module 'grommet-icons/es6/icons/Capacity' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Capacity: Icon
}

declare module 'grommet-icons/es6/icons/Car' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Car: Icon
}

declare module 'grommet-icons/es6/icons/CaretDownFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretDownFill: Icon
}

declare module 'grommet-icons/es6/icons/CaretDown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretDown: Icon
}

declare module 'grommet-icons/es6/icons/CaretLeftFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretLeftFill: Icon
}

declare module 'grommet-icons/es6/icons/CaretNext' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretNext: Icon
}

declare module 'grommet-icons/es6/icons/CaretPrevious' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretPrevious: Icon
}

declare module 'grommet-icons/es6/icons/CaretRightFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretRightFill: Icon
}

declare module 'grommet-icons/es6/icons/CaretUpFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretUpFill: Icon
}

declare module 'grommet-icons/es6/icons/CaretUp' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CaretUp: Icon
}

declare module 'grommet-icons/es6/icons/Cart' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cart: Icon
}

declare module 'grommet-icons/es6/icons/CatalogOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CatalogOption: Icon
}

declare module 'grommet-icons/es6/icons/Catalog' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Catalog: Icon
}

declare module 'grommet-icons/es6/icons/Centos' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Centos: Icon
}

declare module 'grommet-icons/es6/icons/Certificate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Certificate: Icon
}

declare module 'grommet-icons/es6/icons/Channel' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Channel: Icon
}

declare module 'grommet-icons/es6/icons/ChapterAdd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ChapterAdd: Icon
}

declare module 'grommet-icons/es6/icons/ChapterNext' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ChapterNext: Icon
}

declare module 'grommet-icons/es6/icons/ChapterPrevious' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ChapterPrevious: Icon
}

declare module 'grommet-icons/es6/icons/ChatOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ChatOption: Icon
}

declare module 'grommet-icons/es6/icons/Chat' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Chat: Icon
}

declare module 'grommet-icons/es6/icons/CheckboxSelected' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CheckboxSelected: Icon
}

declare module 'grommet-icons/es6/icons/Checkbox' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Checkbox: Icon
}

declare module 'grommet-icons/es6/icons/Checkmark' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Checkmark: Icon
}

declare module 'grommet-icons/es6/icons/Chrome' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Chrome: Icon
}

declare module 'grommet-icons/es6/icons/CircleAlert' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CircleAlert: Icon
}

declare module 'grommet-icons/es6/icons/CircleInformation' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CircleInformation: Icon
}

declare module 'grommet-icons/es6/icons/CirclePlay' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CirclePlay: Icon
}

declare module 'grommet-icons/es6/icons/CircleQuestion' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CircleQuestion: Icon
}

declare module 'grommet-icons/es6/icons/ClearOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ClearOption: Icon
}

declare module 'grommet-icons/es6/icons/Clear' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Clear: Icon
}

declare module 'grommet-icons/es6/icons/Cli' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cli: Icon
}

declare module 'grommet-icons/es6/icons/Clipboard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Clipboard: Icon
}

declare module 'grommet-icons/es6/icons/Clock' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Clock: Icon
}

declare module 'grommet-icons/es6/icons/Clone' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Clone: Icon
}

declare module 'grommet-icons/es6/icons/Close' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Close: Icon
}

declare module 'grommet-icons/es6/icons/ClosedCaption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ClosedCaption: Icon
}

declare module 'grommet-icons/es6/icons/CloudComputer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CloudComputer: Icon
}

declare module 'grommet-icons/es6/icons/CloudDownload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CloudDownload: Icon
}

declare module 'grommet-icons/es6/icons/CloudSoftware' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CloudSoftware: Icon
}

declare module 'grommet-icons/es6/icons/CloudUpload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CloudUpload: Icon
}

declare module 'grommet-icons/es6/icons/Cloud' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cloud: Icon
}

declare module 'grommet-icons/es6/icons/Cloudlinux' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cloudlinux: Icon
}

declare module 'grommet-icons/es6/icons/Cluster' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cluster: Icon
}

declare module 'grommet-icons/es6/icons/CoatCheck' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CoatCheck: Icon
}

declare module 'grommet-icons/es6/icons/CodeSandbox' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CodeSandbox: Icon
}

declare module 'grommet-icons/es6/icons/Code' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Code: Icon
}

declare module 'grommet-icons/es6/icons/Codepen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Codepen: Icon
}

declare module 'grommet-icons/es6/icons/Coffee' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Coffee: Icon
}

declare module 'grommet-icons/es6/icons/Columns' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Columns: Icon
}

declare module 'grommet-icons/es6/icons/Command' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Command: Icon
}

declare module 'grommet-icons/es6/icons/Compare' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Compare: Icon
}

declare module 'grommet-icons/es6/icons/Compass' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Compass: Icon
}

declare module 'grommet-icons/es6/icons/Compliance' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Compliance: Icon
}

declare module 'grommet-icons/es6/icons/Configure' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Configure: Icon
}

declare module 'grommet-icons/es6/icons/Connect' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Connect: Icon
}

declare module 'grommet-icons/es6/icons/Connectivity' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Connectivity: Icon
}

declare module 'grommet-icons/es6/icons/Console' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Console: Icon
}

declare module 'grommet-icons/es6/icons/ContactInfo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ContactInfo: Icon
}

declare module 'grommet-icons/es6/icons/Contact' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Contact: Icon
}

declare module 'grommet-icons/es6/icons/Contract' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Contract: Icon
}

declare module 'grommet-icons/es6/icons/Copy' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Copy: Icon
}

declare module 'grommet-icons/es6/icons/Cpu' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cpu: Icon
}

declare module 'grommet-icons/es6/icons/CreativeCommons' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CreativeCommons: Icon
}

declare module 'grommet-icons/es6/icons/CreditCard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const CreditCard: Icon
}

declare module 'grommet-icons/es6/icons/Css3' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Css3: Icon
}

declare module 'grommet-icons/es6/icons/Cube' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cube: Icon
}

declare module 'grommet-icons/es6/icons/Cubes' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cubes: Icon
}

declare module 'grommet-icons/es6/icons/Currency' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Currency: Icon
}

declare module 'grommet-icons/es6/icons/Cursor' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cursor: Icon
}

declare module 'grommet-icons/es6/icons/Cut' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cut: Icon
}

declare module 'grommet-icons/es6/icons/Cycle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Cycle: Icon
}

declare module 'grommet-icons/es6/icons/Dashboard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dashboard: Icon
}

declare module 'grommet-icons/es6/icons/Database' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Database: Icon
}

declare module 'grommet-icons/es6/icons/Debian' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Debian: Icon
}

declare module 'grommet-icons/es6/icons/Deliver' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Deliver: Icon
}

declare module 'grommet-icons/es6/icons/Deploy' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Deploy: Icon
}

declare module 'grommet-icons/es6/icons/Descend' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Descend: Icon
}

declare module 'grommet-icons/es6/icons/Descending' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Descending: Icon
}

declare module 'grommet-icons/es6/icons/Desktop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Desktop: Icon
}

declare module 'grommet-icons/es6/icons/Detach' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Detach: Icon
}

declare module 'grommet-icons/es6/icons/Device' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Device: Icon
}

declare module 'grommet-icons/es6/icons/Diamond' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Diamond: Icon
}

declare module 'grommet-icons/es6/icons/Directions' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Directions: Icon
}

declare module 'grommet-icons/es6/icons/DisabledOutline' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DisabledOutline: Icon
}

declare module 'grommet-icons/es6/icons/Disc' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Disc: Icon
}

declare module 'grommet-icons/es6/icons/Dislike' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dislike: Icon
}

declare module 'grommet-icons/es6/icons/DislikeFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DislikeFill: Icon
}

declare module 'grommet-icons/es6/icons/Docker' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Docker: Icon
}

declare module 'grommet-icons/es6/icons/DocumentCloud' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentCloud: Icon
}

declare module 'grommet-icons/es6/icons/DocumentConfig' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentConfig: Icon
}

declare module 'grommet-icons/es6/icons/DocumentCsv' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentCsv: Icon
}

declare module 'grommet-icons/es6/icons/DocumentDownload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentDownload: Icon
}

declare module 'grommet-icons/es6/icons/DocumentExcel' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentExcel: Icon
}

declare module 'grommet-icons/es6/icons/DocumentImage' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentImage: Icon
}

declare module 'grommet-icons/es6/icons/DocumentLocked' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentLocked: Icon
}

declare module 'grommet-icons/es6/icons/DocumentMissing' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentMissing: Icon
}

declare module 'grommet-icons/es6/icons/DocumentNotes' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentNotes: Icon
}

declare module 'grommet-icons/es6/icons/DocumentOutlook' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentOutlook: Icon
}

declare module 'grommet-icons/es6/icons/DocumentPdf' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentPdf: Icon
}

declare module 'grommet-icons/es6/icons/DocumentPerformance' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentPerformance: Icon
}

declare module 'grommet-icons/es6/icons/DocumentPpt' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentPpt: Icon
}

declare module 'grommet-icons/es6/icons/DocumentRtf' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentRtf: Icon
}

declare module 'grommet-icons/es6/icons/DocumentSound' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentSound: Icon
}

declare module 'grommet-icons/es6/icons/DocumentStore' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentStore: Icon
}

declare module 'grommet-icons/es6/icons/DocumentTest' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentTest: Icon
}

declare module 'grommet-icons/es6/icons/DocumentText' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentText: Icon
}

declare module 'grommet-icons/es6/icons/DocumentThreat' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentThreat: Icon
}

declare module 'grommet-icons/es6/icons/DocumentTime' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentTime: Icon
}

declare module 'grommet-icons/es6/icons/DocumentTransfer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentTransfer: Icon
}

declare module 'grommet-icons/es6/icons/DocumentTxt' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentTxt: Icon
}

declare module 'grommet-icons/es6/icons/DocumentUpdate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentUpdate: Icon
}

declare module 'grommet-icons/es6/icons/DocumentUpload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentUpload: Icon
}

declare module 'grommet-icons/es6/icons/DocumentUser' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentUser: Icon
}

declare module 'grommet-icons/es6/icons/DocumentVerified' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentVerified: Icon
}

declare module 'grommet-icons/es6/icons/DocumentVideo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentVideo: Icon
}

declare module 'grommet-icons/es6/icons/DocumentWindows' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentWindows: Icon
}

declare module 'grommet-icons/es6/icons/DocumentWord' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentWord: Icon
}

declare module 'grommet-icons/es6/icons/DocumentZip' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DocumentZip: Icon
}

declare module 'grommet-icons/es6/icons/Document' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Document: Icon
}

declare module 'grommet-icons/es6/icons/Domain' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Domain: Icon
}

declare module 'grommet-icons/es6/icons/Dos' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dos: Icon
}

declare module 'grommet-icons/es6/icons/Down' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Down: Icon
}

declare module 'grommet-icons/es6/icons/DownloadOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DownloadOption: Icon
}

declare module 'grommet-icons/es6/icons/Download' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Download: Icon
}

declare module 'grommet-icons/es6/icons/Drag' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Drag: Icon
}

declare module 'grommet-icons/es6/icons/Drawer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Drawer: Icon
}

declare module 'grommet-icons/es6/icons/Dribbble' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dribbble: Icon
}

declare module 'grommet-icons/es6/icons/DriveCage' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const DriveCage: Icon
}

declare module 'grommet-icons/es6/icons/Dropbox' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dropbox: Icon
}

declare module 'grommet-icons/es6/icons/Duplicate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Duplicate: Icon
}

declare module 'grommet-icons/es6/icons/Dxc' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Dxc: Icon
}

declare module 'grommet-icons/es6/icons/Ebay' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ebay: Icon
}

declare module 'grommet-icons/es6/icons/Edge' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Edge: Icon
}

declare module 'grommet-icons/es6/icons/Edit' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Edit: Icon
}

declare module 'grommet-icons/es6/icons/Eject' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Eject: Icon
}

declare module 'grommet-icons/es6/icons/Elevator' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Elevator: Icon
}

declare module 'grommet-icons/es6/icons/Emergency' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Emergency: Icon
}

declare module 'grommet-icons/es6/icons/Emoji' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Emoji: Icon
}

declare module 'grommet-icons/es6/icons/EmptyCircle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const EmptyCircle: Icon
}

declare module 'grommet-icons/es6/icons/Erase' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Erase: Icon
}

declare module 'grommet-icons/es6/icons/Escalator' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Escalator: Icon
}

declare module 'grommet-icons/es6/icons/Expand' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Expand: Icon
}

declare module 'grommet-icons/es6/icons/Ezmeral' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ezmeral: Icon
}

declare module 'grommet-icons/es6/icons/FacebookOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FacebookOption: Icon
}

declare module 'grommet-icons/es6/icons/Facebook' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Facebook: Icon
}

declare module 'grommet-icons/es6/icons/FanOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FanOption: Icon
}

declare module 'grommet-icons/es6/icons/Fan' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Fan: Icon
}

declare module 'grommet-icons/es6/icons/FastForward' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FastForward: Icon
}

declare module 'grommet-icons/es6/icons/Favorite' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Favorite: Icon
}

declare module 'grommet-icons/es6/icons/Fedora' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Fedora: Icon
}

declare module 'grommet-icons/es6/icons/Figma' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Figma: Icon
}

declare module 'grommet-icons/es6/icons/Filter' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Filter: Icon
}

declare module 'grommet-icons/es6/icons/FingerPrint' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FingerPrint: Icon
}

declare module 'grommet-icons/es6/icons/Fireball' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Fireball: Icon
}

declare module 'grommet-icons/es6/icons/Firefox' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Firefox: Icon
}

declare module 'grommet-icons/es6/icons/Firewall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Firewall: Icon
}

declare module 'grommet-icons/es6/icons/FlagFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FlagFill: Icon
}

declare module 'grommet-icons/es6/icons/Flag' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Flag: Icon
}

declare module 'grommet-icons/es6/icons/Flows' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Flows: Icon
}

declare module 'grommet-icons/es6/icons/FolderCycle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FolderCycle: Icon
}

declare module 'grommet-icons/es6/icons/FolderOpen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FolderOpen: Icon
}

declare module 'grommet-icons/es6/icons/Folder' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Folder: Icon
}

declare module 'grommet-icons/es6/icons/FormAdd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormAdd: Icon
}

declare module 'grommet-icons/es6/icons/FormAttachment' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormAttachment: Icon
}

declare module 'grommet-icons/es6/icons/FormCalendar' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormCalendar: Icon
}

declare module 'grommet-icons/es6/icons/FormCheckmark' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormCheckmark: Icon
}

declare module 'grommet-icons/es6/icons/FormClock' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormClock: Icon
}

declare module 'grommet-icons/es6/icons/FormClose' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormClose: Icon
}

declare module 'grommet-icons/es6/icons/FormCut' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormCut: Icon
}

declare module 'grommet-icons/es6/icons/FormDown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormDown: Icon
}

declare module 'grommet-icons/es6/icons/FormEdit' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormEdit: Icon
}

declare module 'grommet-icons/es6/icons/FormFilter' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormFilter: Icon
}

declare module 'grommet-icons/es6/icons/FormFolder' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormFolder: Icon
}

declare module 'grommet-icons/es6/icons/FormLocation' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormLocation: Icon
}

declare module 'grommet-icons/es6/icons/FormLock' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormLock: Icon
}

declare module 'grommet-icons/es6/icons/FormNextLink' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormNextLink: Icon
}

declare module 'grommet-icons/es6/icons/FormNext' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormNext: Icon
}

declare module 'grommet-icons/es6/icons/FormPin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormPin: Icon
}

declare module 'grommet-icons/es6/icons/FormPreviousLink' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormPreviousLink: Icon
}

declare module 'grommet-icons/es6/icons/FormPrevious' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormPrevious: Icon
}

declare module 'grommet-icons/es6/icons/FormRefresh' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormRefresh: Icon
}

declare module 'grommet-icons/es6/icons/FormSchedule' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormSchedule: Icon
}

declare module 'grommet-icons/es6/icons/FormSearch' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormSearch: Icon
}

declare module 'grommet-icons/es6/icons/FormSubtract' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormSubtract: Icon
}

declare module 'grommet-icons/es6/icons/FormTrash' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormTrash: Icon
}

declare module 'grommet-icons/es6/icons/FormUp' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormUp: Icon
}

declare module 'grommet-icons/es6/icons/FormUpload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormUpload: Icon
}

declare module 'grommet-icons/es6/icons/FormViewHide' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormViewHide: Icon
}

declare module 'grommet-icons/es6/icons/FormView' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const FormView: Icon
}

declare module 'grommet-icons/es6/icons/ForwardTen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ForwardTen: Icon
}

declare module 'grommet-icons/es6/icons/Freebsd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Freebsd: Icon
}

declare module 'grommet-icons/es6/icons/Gallery' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gallery: Icon
}

declare module 'grommet-icons/es6/icons/Gamepad' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gamepad: Icon
}

declare module 'grommet-icons/es6/icons/Gateway' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gateway: Icon
}

declare module 'grommet-icons/es6/icons/Gatsbyjs' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gatsbyjs: Icon
}

declare module 'grommet-icons/es6/icons/Gem' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gem: Icon
}

declare module 'grommet-icons/es6/icons/Gift' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gift: Icon
}

declare module 'grommet-icons/es6/icons/Github' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Github: Icon
}

declare module 'grommet-icons/es6/icons/Globe' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Globe: Icon
}

declare module 'grommet-icons/es6/icons/Golang' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Golang: Icon
}

declare module 'grommet-icons/es6/icons/GooglePlay' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const GooglePlay: Icon
}

declare module 'grommet-icons/es6/icons/GooglePlus' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const GooglePlus: Icon
}

declare module 'grommet-icons/es6/icons/GoogleWallet' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const GoogleWallet: Icon
}

declare module 'grommet-icons/es6/icons/Google' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Google: Icon
}

declare module 'grommet-icons/es6/icons/GraphQl' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const GraphQl: Icon
}

declare module 'grommet-icons/es6/icons/Gremlin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Gremlin: Icon
}

declare module 'grommet-icons/es6/icons/Grid' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Grid: Icon
}

declare module 'grommet-icons/es6/icons/Grommet' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Grommet: Icon
}

declare module 'grommet-icons/es6/icons/Group' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Group: Icon
}

declare module 'grommet-icons/es6/icons/Grow' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Grow: Icon
}

declare module 'grommet-icons/es6/icons/Hadoop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Hadoop: Icon
}

declare module 'grommet-icons/es6/icons/Halt' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Halt: Icon
}

declare module 'grommet-icons/es6/icons/HelpOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const HelpOption: Icon
}

declare module 'grommet-icons/es6/icons/Help' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Help: Icon
}

declare module 'grommet-icons/es6/icons/Heroku' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Heroku: Icon
}

declare module 'grommet-icons/es6/icons/Hide' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Hide: Icon
}

declare module 'grommet-icons/es6/icons/History' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const History: Icon
}

declare module 'grommet-icons/es6/icons/HomeOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const HomeOption: Icon
}

declare module 'grommet-icons/es6/icons/HomeRounded' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const HomeRounded: Icon
}

declare module 'grommet-icons/es6/icons/Home' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Home: Icon
}

declare module 'grommet-icons/es6/icons/Horton' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Horton: Icon
}

declare module 'grommet-icons/es6/icons/HostMaintenance' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const HostMaintenance: Icon
}

declare module 'grommet-icons/es6/icons/Host' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Host: Icon
}

declare module 'grommet-icons/es6/icons/Hp' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Hp: Icon
}

declare module 'grommet-icons/es6/icons/HpeLabs' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const HpeLabs: Icon
}

declare module 'grommet-icons/es6/icons/Hpe' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Hpe: Icon
}

declare module 'grommet-icons/es6/icons/Hpi' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Hpi: Icon
}

declare module 'grommet-icons/es6/icons/Html5' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Html5: Icon
}

declare module 'grommet-icons/es6/icons/IceCream' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const IceCream: Icon
}

declare module 'grommet-icons/es6/icons/Image' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Image: Icon
}

declare module 'grommet-icons/es6/icons/Impact' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Impact: Icon
}

declare module 'grommet-icons/es6/icons/InProgress' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const InProgress: Icon
}

declare module 'grommet-icons/es6/icons/Inbox' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Inbox: Icon
}

declare module 'grommet-icons/es6/icons/Indicator' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Indicator: Icon
}

declare module 'grommet-icons/es6/icons/Info' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Info: Icon
}

declare module 'grommet-icons/es6/icons/Inherit' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Inherit: Icon
}

declare module 'grommet-icons/es6/icons/Insecure' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Insecure: Icon
}

declare module 'grommet-icons/es6/icons/Inspect' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Inspect: Icon
}

declare module 'grommet-icons/es6/icons/Instagram' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Instagram: Icon
}

declare module 'grommet-icons/es6/icons/InstallOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const InstallOption: Icon
}

declare module 'grommet-icons/es6/icons/Install' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Install: Icon
}

declare module 'grommet-icons/es6/icons/Integration' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Integration: Icon
}

declare module 'grommet-icons/es6/icons/InternetExplorer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const InternetExplorer: Icon
}

declare module 'grommet-icons/es6/icons/Italic' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Italic: Icon
}

declare module 'grommet-icons/es6/icons/Iteration' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Iteration: Icon
}

declare module 'grommet-icons/es6/icons/Java' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Java: Icon
}

declare module 'grommet-icons/es6/icons/Js' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Js: Icon
}

declare module 'grommet-icons/es6/icons/Key' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Key: Icon
}

declare module 'grommet-icons/es6/icons/Keyboard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Keyboard: Icon
}

declare module 'grommet-icons/es6/icons/Language' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Language: Icon
}

declare module 'grommet-icons/es6/icons/Lastfm' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Lastfm: Icon
}

declare module 'grommet-icons/es6/icons/Launch' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Launch: Icon
}

declare module 'grommet-icons/es6/icons/Layer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Layer: Icon
}

declare module 'grommet-icons/es6/icons/License' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const License: Icon
}

declare module 'grommet-icons/es6/icons/Like' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Like: Icon
}

declare module 'grommet-icons/es6/icons/LikeFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LikeFill: Icon
}

declare module 'grommet-icons/es6/icons/LineChart' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LineChart: Icon
}

declare module 'grommet-icons/es6/icons/LinkBottom' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkBottom: Icon
}

declare module 'grommet-icons/es6/icons/LinkDown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkDown: Icon
}

declare module 'grommet-icons/es6/icons/LinkNext' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkNext: Icon
}

declare module 'grommet-icons/es6/icons/LinkPrevious' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkPrevious: Icon
}

declare module 'grommet-icons/es6/icons/LinkTop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkTop: Icon
}

declare module 'grommet-icons/es6/icons/LinkUp' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkUp: Icon
}

declare module 'grommet-icons/es6/icons/Link' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Link: Icon
}

declare module 'grommet-icons/es6/icons/LinkedinOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LinkedinOption: Icon
}

declare module 'grommet-icons/es6/icons/Linkedin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Linkedin: Icon
}

declare module 'grommet-icons/es6/icons/List' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const List: Icon
}

declare module 'grommet-icons/es6/icons/Local' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Local: Icon
}

declare module 'grommet-icons/es6/icons/LocationPin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const LocationPin: Icon
}

declare module 'grommet-icons/es6/icons/Location' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Location: Icon
}

declare module 'grommet-icons/es6/icons/Lock' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Lock: Icon
}

declare module 'grommet-icons/es6/icons/Login' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Login: Icon
}

declare module 'grommet-icons/es6/icons/Logout' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Logout: Icon
}

declare module 'grommet-icons/es6/icons/Lounge' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Lounge: Icon
}

declare module 'grommet-icons/es6/icons/Magic' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Magic: Icon
}

declare module 'grommet-icons/es6/icons/MailOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const MailOption: Icon
}

declare module 'grommet-icons/es6/icons/Mail' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Mail: Icon
}

declare module 'grommet-icons/es6/icons/Mandriva' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Mandriva: Icon
}

declare module 'grommet-icons/es6/icons/Manual' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Manual: Icon
}

declare module 'grommet-icons/es6/icons/MapLocation' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const MapLocation: Icon
}

declare module 'grommet-icons/es6/icons/Map' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Map: Icon
}

declare module 'grommet-icons/es6/icons/Mastercard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Mastercard: Icon
}

declare module 'grommet-icons/es6/icons/Medium' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Medium: Icon
}

declare module 'grommet-icons/es6/icons/Memory' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Memory: Icon
}

declare module 'grommet-icons/es6/icons/Menu' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Menu: Icon
}

declare module 'grommet-icons/es6/icons/Microfocus' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Microfocus: Icon
}

declare module 'grommet-icons/es6/icons/Microphone' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Microphone: Icon
}

declare module 'grommet-icons/es6/icons/Money' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Money: Icon
}

declare module 'grommet-icons/es6/icons/Monitor' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Monitor: Icon
}

declare module 'grommet-icons/es6/icons/Monospace' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Monospace: Icon
}

declare module 'grommet-icons/es6/icons/Moon' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Moon: Icon
}

declare module 'grommet-icons/es6/icons/MoreVertical' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const MoreVertical: Icon
}

declare module 'grommet-icons/es6/icons/More' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const More: Icon
}

declare module 'grommet-icons/es6/icons/Mouse' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Mouse: Icon
}

declare module 'grommet-icons/es6/icons/Multimedia' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Multimedia: Icon
}

declare module 'grommet-icons/es6/icons/Multiple' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Multiple: Icon
}

declare module 'grommet-icons/es6/icons/Music' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Music: Icon
}

declare module 'grommet-icons/es6/icons/Mysql' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Mysql: Icon
}

declare module 'grommet-icons/es6/icons/Navigate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Navigate: Icon
}

declare module 'grommet-icons/es6/icons/NetworkDrive' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const NetworkDrive: Icon
}

declare module 'grommet-icons/es6/icons/Network' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Network: Icon
}

declare module 'grommet-icons/es6/icons/NewWindow' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const NewWindow: Icon
}

declare module 'grommet-icons/es6/icons/New' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const New: Icon
}

declare module 'grommet-icons/es6/icons/Next' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Next: Icon
}

declare module 'grommet-icons/es6/icons/Node' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Node: Icon
}

declare module 'grommet-icons/es6/icons/Nodes' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Nodes: Icon
}

declare module 'grommet-icons/es6/icons/Norton' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Norton: Icon
}

declare module 'grommet-icons/es6/icons/Note' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Note: Icon
}

declare module 'grommet-icons/es6/icons/Notes' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Notes: Icon
}

declare module 'grommet-icons/es6/icons/Notification' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Notification: Icon
}

declare module 'grommet-icons/es6/icons/Npm' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Npm: Icon
}

declare module 'grommet-icons/es6/icons/ObjectGroup' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ObjectGroup: Icon
}

declare module 'grommet-icons/es6/icons/ObjectUngroup' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ObjectUngroup: Icon
}

declare module 'grommet-icons/es6/icons/OfflineStorage' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const OfflineStorage: Icon
}

declare module 'grommet-icons/es6/icons/Onedrive' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Onedrive: Icon
}

declare module 'grommet-icons/es6/icons/Opera' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Opera: Icon
}

declare module 'grommet-icons/es6/icons/Optimize' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Optimize: Icon
}

declare module 'grommet-icons/es6/icons/Oracle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Oracle: Icon
}

declare module 'grommet-icons/es6/icons/OrderedList' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const OrderedList: Icon
}

declare module 'grommet-icons/es6/icons/Organization' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Organization: Icon
}

declare module 'grommet-icons/es6/icons/Overview' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Overview: Icon
}

declare module 'grommet-icons/es6/icons/Package' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Package: Icon
}

declare module 'grommet-icons/es6/icons/Paint' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Paint: Icon
}

declare module 'grommet-icons/es6/icons/Pan' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Pan: Icon
}

declare module 'grommet-icons/es6/icons/PauseFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PauseFill: Icon
}

declare module 'grommet-icons/es6/icons/Pause' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Pause: Icon
}

declare module 'grommet-icons/es6/icons/Paypal' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Paypal: Icon
}

declare module 'grommet-icons/es6/icons/Performance' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Performance: Icon
}

declare module 'grommet-icons/es6/icons/PersonalComputer' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PersonalComputer: Icon
}

declare module 'grommet-icons/es6/icons/PhoneFlip' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PhoneFlip: Icon
}

declare module 'grommet-icons/es6/icons/PhoneHorizontal' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PhoneHorizontal: Icon
}

declare module 'grommet-icons/es6/icons/PhoneVertical' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PhoneVertical: Icon
}

declare module 'grommet-icons/es6/icons/Phone' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Phone: Icon
}

declare module 'grommet-icons/es6/icons/PieChart' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PieChart: Icon
}

declare module 'grommet-icons/es6/icons/PiedPiper' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PiedPiper: Icon
}

declare module 'grommet-icons/es6/icons/Pin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Pin: Icon
}

declare module 'grommet-icons/es6/icons/Pinterest' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Pinterest: Icon
}

declare module 'grommet-icons/es6/icons/Plan' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Plan: Icon
}

declare module 'grommet-icons/es6/icons/PlayFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PlayFill: Icon
}

declare module 'grommet-icons/es6/icons/Play' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Play: Icon
}

declare module 'grommet-icons/es6/icons/Plug' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Plug: Icon
}

declare module 'grommet-icons/es6/icons/Pocket' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Pocket: Icon
}

declare module 'grommet-icons/es6/icons/PowerCycle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PowerCycle: Icon
}

declare module 'grommet-icons/es6/icons/PowerForceShutdown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PowerForceShutdown: Icon
}

declare module 'grommet-icons/es6/icons/PowerReset' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PowerReset: Icon
}

declare module 'grommet-icons/es6/icons/PowerShutdown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const PowerShutdown: Icon
}

declare module 'grommet-icons/es6/icons/Power' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Power: Icon
}

declare module 'grommet-icons/es6/icons/Previous' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Previous: Icon
}

declare module 'grommet-icons/es6/icons/Print' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Print: Icon
}

declare module 'grommet-icons/es6/icons/ProductHunt' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ProductHunt: Icon
}

declare module 'grommet-icons/es6/icons/Projects' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Projects: Icon
}

declare module 'grommet-icons/es6/icons/Qr' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Qr: Icon
}

declare module 'grommet-icons/es6/icons/RadialSelected' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const RadialSelected: Icon
}

declare module 'grommet-icons/es6/icons/Radial' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Radial: Icon
}

declare module 'grommet-icons/es6/icons/Raspberry' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Raspberry: Icon
}

declare module 'grommet-icons/es6/icons/Reactjs' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Reactjs: Icon
}

declare module 'grommet-icons/es6/icons/Reddit' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Reddit: Icon
}

declare module 'grommet-icons/es6/icons/Redhat' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Redhat: Icon
}

declare module 'grommet-icons/es6/icons/Redo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Redo: Icon
}

declare module 'grommet-icons/es6/icons/Refresh' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Refresh: Icon
}

declare module 'grommet-icons/es6/icons/Resources' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Resources: Icon
}

declare module 'grommet-icons/es6/icons/Restaurant' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Restaurant: Icon
}

declare module 'grommet-icons/es6/icons/RestroomMen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const RestroomMen: Icon
}

declare module 'grommet-icons/es6/icons/RestroomWomen' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const RestroomWomen: Icon
}

declare module 'grommet-icons/es6/icons/Restroom' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Restroom: Icon
}

declare module 'grommet-icons/es6/icons/Resume' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Resume: Icon
}

declare module 'grommet-icons/es6/icons/Return' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Return: Icon
}

declare module 'grommet-icons/es6/icons/Revert' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Revert: Icon
}

declare module 'grommet-icons/es6/icons/Rewind' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Rewind: Icon
}

declare module 'grommet-icons/es6/icons/Risk' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Risk: Icon
}

declare module 'grommet-icons/es6/icons/Robot' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Robot: Icon
}

declare module 'grommet-icons/es6/icons/RotateLeft' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const RotateLeft: Icon
}

declare module 'grommet-icons/es6/icons/RotateRight' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const RotateRight: Icon
}

declare module 'grommet-icons/es6/icons/Rss' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Rss: Icon
}

declare module 'grommet-icons/es6/icons/Run' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Run: Icon
}

declare module 'grommet-icons/es6/icons/SafariOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const SafariOption: Icon
}

declare module 'grommet-icons/es6/icons/Sans' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sans: Icon
}

declare module 'grommet-icons/es6/icons/Satellite' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Satellite: Icon
}

declare module 'grommet-icons/es6/icons/Save' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Save: Icon
}

declare module 'grommet-icons/es6/icons/Scan' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Scan: Icon
}

declare module 'grommet-icons/es6/icons/ScheduleNew' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ScheduleNew: Icon
}

declare module 'grommet-icons/es6/icons/SchedulePlay' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const SchedulePlay: Icon
}

declare module 'grommet-icons/es6/icons/Schedule' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Schedule: Icon
}

declare module 'grommet-icons/es6/icons/Schedules' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Schedules: Icon
}

declare module 'grommet-icons/es6/icons/Sco' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sco: Icon
}

declare module 'grommet-icons/es6/icons/Scorecard' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Scorecard: Icon
}

declare module 'grommet-icons/es6/icons/Script' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Script: Icon
}

declare module 'grommet-icons/es6/icons/Sd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sd: Icon
}

declare module 'grommet-icons/es6/icons/SearchAdvanced' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const SearchAdvanced: Icon
}

declare module 'grommet-icons/es6/icons/Search' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Search: Icon
}

declare module 'grommet-icons/es6/icons/Secure' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Secure: Icon
}

declare module 'grommet-icons/es6/icons/Select' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Select: Icon
}

declare module 'grommet-icons/es6/icons/Selection' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Selection: Icon
}

declare module 'grommet-icons/es6/icons/Semantics' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Semantics: Icon
}

declare module 'grommet-icons/es6/icons/Send' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Send: Icon
}

declare module 'grommet-icons/es6/icons/ServerCluster' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ServerCluster: Icon
}

declare module 'grommet-icons/es6/icons/Server' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Server: Icon
}

declare module 'grommet-icons/es6/icons/Servers' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Servers: Icon
}

declare module 'grommet-icons/es6/icons/ServicePlay' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ServicePlay: Icon
}

declare module 'grommet-icons/es6/icons/Services' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Services: Icon
}

declare module 'grommet-icons/es6/icons/SettingsOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const SettingsOption: Icon
}

declare module 'grommet-icons/es6/icons/ShareOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ShareOption: Icon
}

declare module 'grommet-icons/es6/icons/ShareRounded' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ShareRounded: Icon
}

declare module 'grommet-icons/es6/icons/Share' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Share: Icon
}

declare module 'grommet-icons/es6/icons/ShieldSecurity' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ShieldSecurity: Icon
}

declare module 'grommet-icons/es6/icons/Shield' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Shield: Icon
}

declare module 'grommet-icons/es6/icons/Shift' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Shift: Icon
}

declare module 'grommet-icons/es6/icons/Shop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Shop: Icon
}

declare module 'grommet-icons/es6/icons/Sidebar' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sidebar: Icon
}

declare module 'grommet-icons/es6/icons/Sign' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sign: Icon
}

declare module 'grommet-icons/es6/icons/Skype' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Skype: Icon
}

declare module 'grommet-icons/es6/icons/Slack' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Slack: Icon
}

declare module 'grommet-icons/es6/icons/Snapchat' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Snapchat: Icon
}

declare module 'grommet-icons/es6/icons/Solaris' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Solaris: Icon
}

declare module 'grommet-icons/es6/icons/Sort' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sort: Icon
}

declare module 'grommet-icons/es6/icons/Soundcloud' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Soundcloud: Icon
}

declare module 'grommet-icons/es6/icons/Spa' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Spa: Icon
}

declare module 'grommet-icons/es6/icons/Spectrum' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Spectrum: Icon
}

declare module 'grommet-icons/es6/icons/Split' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Split: Icon
}

declare module 'grommet-icons/es6/icons/Splits' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Splits: Icon
}

declare module 'grommet-icons/es6/icons/Spotify' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Spotify: Icon
}

declare module 'grommet-icons/es6/icons/Square' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Square: Icon
}

declare module 'grommet-icons/es6/icons/StackOverflow' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StackOverflow: Icon
}

declare module 'grommet-icons/es6/icons/Stakeholder' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Stakeholder: Icon
}

declare module 'grommet-icons/es6/icons/StarHalf' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StarHalf: Icon
}

declare module 'grommet-icons/es6/icons/Star' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Star: Icon
}

declare module 'grommet-icons/es6/icons/StarOutline' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StarOutline: Icon
}

declare module 'grommet-icons/es6/icons/StatusCriticalSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusCriticalSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusCritical' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusCritical: Icon
}

declare module 'grommet-icons/es6/icons/StatusDisabledSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusDisabledSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusDisabled' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusDisabled: Icon
}

declare module 'grommet-icons/es6/icons/StatusGoodSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusGoodSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusGood' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusGood: Icon
}

declare module 'grommet-icons/es6/icons/StatusInfoSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusInfoSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusInfo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusInfo: Icon
}

declare module 'grommet-icons/es6/icons/StatusPlaceholderSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusPlaceholderSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusPlaceholder' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusPlaceholder: Icon
}

declare module 'grommet-icons/es6/icons/StatusUnknownSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusUnknownSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusUnknown' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusUnknown: Icon
}

declare module 'grommet-icons/es6/icons/StatusWarningSmall' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusWarningSmall: Icon
}

declare module 'grommet-icons/es6/icons/StatusWarning' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StatusWarning: Icon
}

declare module 'grommet-icons/es6/icons/StepsOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StepsOption: Icon
}

declare module 'grommet-icons/es6/icons/Steps' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Steps: Icon
}

declare module 'grommet-icons/es6/icons/StopFill' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StopFill: Icon
}

declare module 'grommet-icons/es6/icons/Stop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Stop: Icon
}

declare module 'grommet-icons/es6/icons/Storage' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Storage: Icon
}

declare module 'grommet-icons/es6/icons/StreetView' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StreetView: Icon
}

declare module 'grommet-icons/es6/icons/StrikeThrough' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const StrikeThrough: Icon
}

declare module 'grommet-icons/es6/icons/Stripe' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Stripe: Icon
}

declare module 'grommet-icons/es6/icons/Subscript' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Subscript: Icon
}

declare module 'grommet-icons/es6/icons/SubtractCircle' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const SubtractCircle: Icon
}

declare module 'grommet-icons/es6/icons/Subtract' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Subtract: Icon
}

declare module 'grommet-icons/es6/icons/Sun' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sun: Icon
}

declare module 'grommet-icons/es6/icons/Superscript' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Superscript: Icon
}

declare module 'grommet-icons/es6/icons/Support' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Support: Icon
}

declare module 'grommet-icons/es6/icons/Suse' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Suse: Icon
}

declare module 'grommet-icons/es6/icons/Swift' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Swift: Icon
}

declare module 'grommet-icons/es6/icons/Swim' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Swim: Icon
}

declare module 'grommet-icons/es6/icons/Switch' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Switch: Icon
}

declare module 'grommet-icons/es6/icons/Sync' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Sync: Icon
}

declare module 'grommet-icons/es6/icons/System' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const System: Icon
}

declare module 'grommet-icons/es6/icons/TableAdd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TableAdd: Icon
}

declare module 'grommet-icons/es6/icons/Table' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Table: Icon
}

declare module 'grommet-icons/es6/icons/Tag' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tag: Icon
}

declare module 'grommet-icons/es6/icons/TapeOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TapeOption: Icon
}

declare module 'grommet-icons/es6/icons/Tape' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tape: Icon
}

declare module 'grommet-icons/es6/icons/Target' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Target: Icon
}

declare module 'grommet-icons/es6/icons/Task' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Task: Icon
}

declare module 'grommet-icons/es6/icons/Tasks' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tasks: Icon
}

declare module 'grommet-icons/es6/icons/Technology' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Technology: Icon
}

declare module 'grommet-icons/es6/icons/Template' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Template: Icon
}

declare module 'grommet-icons/es6/icons/Terminal' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Terminal: Icon
}

declare module 'grommet-icons/es6/icons/TestDesktop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TestDesktop: Icon
}

declare module 'grommet-icons/es6/icons/Test' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Test: Icon
}

declare module 'grommet-icons/es6/icons/TextAlignCenter' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TextAlignCenter: Icon
}

declare module 'grommet-icons/es6/icons/TextAlignFull' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TextAlignFull: Icon
}

declare module 'grommet-icons/es6/icons/TextAlignLeft' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TextAlignLeft: Icon
}

declare module 'grommet-icons/es6/icons/TextAlignRight' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TextAlignRight: Icon
}

declare module 'grommet-icons/es6/icons/TextWrap' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TextWrap: Icon
}

declare module 'grommet-icons/es6/icons/Threats' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Threats: Icon
}

declare module 'grommet-icons/es6/icons/ThreeDffects' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ThreeDffects: Icon
}

declare module 'grommet-icons/es6/icons/ThreeD' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ThreeD: Icon
}

declare module 'grommet-icons/es6/icons/Ticket' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ticket: Icon
}

declare module 'grommet-icons/es6/icons/Tiktok' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tiktok: Icon
}

declare module 'grommet-icons/es6/icons/Time' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Time: Icon
}

declare module 'grommet-icons/es6/icons/Tip' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tip: Icon
}

declare module 'grommet-icons/es6/icons/Toast' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Toast: Icon
}

declare module 'grommet-icons/es6/icons/Tools' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tools: Icon
}

declare module 'grommet-icons/es6/icons/Tooltip' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tooltip: Icon
}

declare module 'grommet-icons/es6/icons/TopCorner' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TopCorner: Icon
}

declare module 'grommet-icons/es6/icons/Train' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Train: Icon
}

declare module 'grommet-icons/es6/icons/Transaction' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Transaction: Icon
}

declare module 'grommet-icons/es6/icons/Trash' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Trash: Icon
}

declare module 'grommet-icons/es6/icons/TreeOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const TreeOption: Icon
}

declare module 'grommet-icons/es6/icons/Tree' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tree: Icon
}

declare module 'grommet-icons/es6/icons/Trigger' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Trigger: Icon
}

declare module 'grommet-icons/es6/icons/Trophy' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Trophy: Icon
}

declare module 'grommet-icons/es6/icons/Troubleshoot' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Troubleshoot: Icon
}

declare module 'grommet-icons/es6/icons/Tty' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tty: Icon
}

declare module 'grommet-icons/es6/icons/Tumblr' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Tumblr: Icon
}

declare module 'grommet-icons/es6/icons/Turbolinux' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Turbolinux: Icon
}

declare module 'grommet-icons/es6/icons/Twitter' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Twitter: Icon
}

declare module 'grommet-icons/es6/icons/Ubuntu' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Ubuntu: Icon
}

declare module 'grommet-icons/es6/icons/Underline' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Underline: Icon
}

declare module 'grommet-icons/es6/icons/Undo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Undo: Icon
}

declare module 'grommet-icons/es6/icons/Unlink' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Unlink: Icon
}

declare module 'grommet-icons/es6/icons/Unlock' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Unlock: Icon
}

declare module 'grommet-icons/es6/icons/UnorderedList' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UnorderedList: Icon
}

declare module 'grommet-icons/es6/icons/Unsorted' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Unsorted: Icon
}

declare module 'grommet-icons/es6/icons/Up' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Up: Icon
}

declare module 'grommet-icons/es6/icons/Update' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Update: Icon
}

declare module 'grommet-icons/es6/icons/Upgrade' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Upgrade: Icon
}

declare module 'grommet-icons/es6/icons/UploadOption' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UploadOption: Icon
}

declare module 'grommet-icons/es6/icons/Upload' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Upload: Icon
}

declare module 'grommet-icons/es6/icons/UsbKey' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UsbKey: Icon
}

declare module 'grommet-icons/es6/icons/UserAdd' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserAdd: Icon
}

declare module 'grommet-icons/es6/icons/UserAdmin' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserAdmin: Icon
}

declare module 'grommet-icons/es6/icons/UserExpert' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserExpert: Icon
}

declare module 'grommet-icons/es6/icons/UserFemale' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserFemale: Icon
}

declare module 'grommet-icons/es6/icons/UserManager' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserManager: Icon
}

declare module 'grommet-icons/es6/icons/UserNew' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserNew: Icon
}

declare module 'grommet-icons/es6/icons/UserPolice' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserPolice: Icon
}

declare module 'grommet-icons/es6/icons/UserSettings' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserSettings: Icon
}

declare module 'grommet-icons/es6/icons/UserWorker' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const UserWorker: Icon
}

declare module 'grommet-icons/es6/icons/User' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const User: Icon
}

declare module 'grommet-icons/es6/icons/Validate' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Validate: Icon
}

declare module 'grommet-icons/es6/icons/Vend' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Vend: Icon
}

declare module 'grommet-icons/es6/icons/Video' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Video: Icon
}

declare module 'grommet-icons/es6/icons/View' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const View: Icon
}

declare module 'grommet-icons/es6/icons/Vimeo' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Vimeo: Icon
}

declare module 'grommet-icons/es6/icons/VirtualMachine' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VirtualMachine: Icon
}

declare module 'grommet-icons/es6/icons/VirtualStorage' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VirtualStorage: Icon
}

declare module 'grommet-icons/es6/icons/Visa' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Visa: Icon
}

declare module 'grommet-icons/es6/icons/VmMaintenance' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VmMaintenance: Icon
}

declare module 'grommet-icons/es6/icons/Vmware' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Vmware: Icon
}

declare module 'grommet-icons/es6/icons/VolumeControl' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VolumeControl: Icon
}

declare module 'grommet-icons/es6/icons/VolumeLow' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VolumeLow: Icon
}

declare module 'grommet-icons/es6/icons/VolumeMute' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const VolumeMute: Icon
}

declare module 'grommet-icons/es6/icons/Volume' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Volume: Icon
}

declare module 'grommet-icons/es6/icons/Vulnerability' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Vulnerability: Icon
}

declare module 'grommet-icons/es6/icons/Waypoint' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Waypoint: Icon
}

declare module 'grommet-icons/es6/icons/Webcam' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Webcam: Icon
}

declare module 'grommet-icons/es6/icons/WheelchairActive' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const WheelchairActive: Icon
}

declare module 'grommet-icons/es6/icons/Wheelchair' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Wheelchair: Icon
}

declare module 'grommet-icons/es6/icons/WifiLow' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const WifiLow: Icon
}

declare module 'grommet-icons/es6/icons/WifiMedium' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const WifiMedium: Icon
}

declare module 'grommet-icons/es6/icons/WifiNone' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const WifiNone: Icon
}

declare module 'grommet-icons/es6/icons/Wifi' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Wifi: Icon
}

declare module 'grommet-icons/es6/icons/WindowsLegacy' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const WindowsLegacy: Icon
}

declare module 'grommet-icons/es6/icons/Windows' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Windows: Icon
}

declare module 'grommet-icons/es6/icons/Wordpress' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Wordpress: Icon
}

declare module 'grommet-icons/es6/icons/Workshop' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Workshop: Icon
}

declare module 'grommet-icons/es6/icons/Yoga' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Yoga: Icon
}

declare module 'grommet-icons/es6/icons/Youtube' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Youtube: Icon
}

declare module 'grommet-icons/es6/icons/ZoomIn' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ZoomIn: Icon
}

declare module 'grommet-icons/es6/icons/ZoomOut' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const ZoomOut: Icon
}

declare module 'grommet-icons/es6/icons/Zoom' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Zoom: Icon
}

declare module 'grommet-icons/es6/icons/Blank' {
  import { Icon } from 'grommet-icons/es6/icons'
  export declare const Blank: Icon
}
